### ISSUE TITLE
Country is marked invalid if it contains non-ascii characters

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/BMRBDep#113]
This opens up a can of worms. We have two obvious options:

* Do some sort of automatic/manual filtering of the country and province names to remove non-ascii characters prior to displaying them to the user. This will probably be hard to implement properly in JavaScript, and manual remediation would prevent us from getting updates when countries and state/provinces change.

* Update the data type for these to allow anything, and then convert out the unicode during the deposition step. I think this is the better option, as we can capture unicode in the deposition and convert it when we import into the annotation pipeline. This way we can always reference the original values. This also would allow unicode author names.

**Comment by dmaziuk** [comment]
We have a validation rule that flags non-ascii characters, by our current standard they make nmr-star invalid.

**Comment by jonwedell** [comment]
Indeed. The final entry will only contain ascii characters. It is just a question of whether to convert/filter them upon deposition, or try to prevent them from being entered in the first place.

**Comment by dmaziuk** [comment]
I think letting them enter non-ascii char and then sending back the converted version is more confusing than an error message that pops up right away,

**Comment by jonwedell** [comment]
I tend to agree, the problem is specifically with the country/state forms. The actual countries have non-ascii characters in them, and converting these to their "nearest ascii neighbor" is going to be a lot harder in TypeScript than in Python (which I know has a module for it). Due to the way the JavaScript auto-filling country module we use gets injected into the project, it might even be impossible.

I can probably disallow unicode for everything but these fields, and then convert them upon deposition.

**Comment by dmaziuk** [comment]
Personally I don't know why we're even collecting all that in the first place: we only use e-mail these days and have for as long as I can remember.

Can you use 2-letter country codes instead? Those are ascii, and we should be able to convert to full names (or leave 'em be) in the post-cooking.

**Comment by jonwedell** [comment]
I could, but in the "convert to full names" step we still have the problem that some country names have non-ascii characters in them. We have to perform the filtering/converting/mapping of these characters at some point - unless we switched to only storing country codes in the first place (which is fine with me) - though state/province names still would have the problem.

I agree this information is not strictly needed anymore, but at least the country is nice in order to make a map showing where our depositions come from.

**Comment by jonwedell** [comment]
Unicode stripping during deposition confirmed working.
