### ISSUE TITLE
Can't cut or copy and paste

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#116]
If you want to cut or copy and paste within the text fields you cannot. For example copying from one text field and pasting it in another text field. I am not sure how large of an issue this is since you can duplicate a section if you need the same information.

**Comment by jonwedell** [comment]
This is only for open enumerations, and it has to be that way in order to get all enumerations to suggest when you click into the field. (It stores the value, but removes it from the field, and then restores it later if you don't make changes.)
