### ISSUE TITLE
Session Overlap/ Not Loading

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#121]
I know we had spoken about this on Friday Jon, but this issue occurred again. I had clicked on the "create new deposition" on the side bar while I was within another entry. It brought me to the normal home screen and indicated I had a previous entry open (the open I had just left) per usual. When I then entered my email a nickname etc. it opened up the new entry (I had done an auto fill one). The information from the auto fill was all there, but the first page was referring to the entry I had previously left. It had order parameters up, which the new entry did not contain (I have a screen shot below). 
<strike>
After this I decided to end the session just to see if the old one would pop up again or if it would indicate that I had the old one still active on the homepage. It did not indicate that I had the old one active. Now when I go to the emails to start working on either again with the provided links it loads what appears to be indefinitely (at least 20 minutes). </strike>

I have the deposition codes from the URLs included below too.
First one: 872cf293-e0f1-453b-b996-5fc8e1e0516d "Testing 27722"
URL: https://dev-bmrbdep.bmrb.wisc.edu/entry/load/872cf293-e0f1-453b-b996-5fc8e1e0516d

Second one: 6a8be558-77da-44be-bdc8-bc7e8f579f89 "testing existing 27705"
URL: https://dev-bmrbdep.bmrb.wisc.edu/entry/load/6a8be558-77da-44be-bdc8-bc7e8f579f89

![1](https://user-images.githubusercontent.com/44450691/55915278-ef601780-5bae-11e9-9ab7-2a935e2929cc.png)
![2](https://user-images.githubusercontent.com/44450691/55915283-f1c27180-5bae-11e9-9544-952f93592b06.png)

**Comment by jonwedell** [comment]
These should both be fixed. The second is a totally separate issue.

As an aside, I changed a lot of the session handling code this week to try to better handle the case where the user makes changes from two browsers at once. If you get an error message that you don't think you should, or experience any other new weird behavior, please let me know.

**Comment by rsiegl** [comment]
I can confirm that I can now access both of the entries. 

(1)The new issue that appears is that If I have both of them up in different tabs, then open a third tab and go to the home page it shows the last loaded entry as the in progress deposition. 

(2)Furthermore when I go to the entry tab that loaded first and reload that page it brings up the entry that loaded second or last. 

Maybe there could be multiple in progress entries on the homepage, but I am not sure how that will effect issue 2 here? (I included numbers for both of these issues so they are easier to mention.)

**Comment by jonwedell** [comment]
It is not my intention to support two different depositions open in two tabs at once. The behavior that you describe is expected: only the last accessed entry will be "live" at any given time.

I will think about how I can detect if users are trying to open two entries in two different tabs such that I can display an error, or log one of them out.

**Comment by rsiegl** [comment]
I am not sure how feasible this is, but could the session be ended simply if someone leaves the deposition page or exits out of the tab/page? That would ensure that no matter when they leave the page, regardless of ending the session, the session would be ended.

**Comment by jonwedell** [comment]
Yes, but I think it would be more helpful for people to be able to resume their deposition just by returning to the BMRBDep web page. Otherwise they would always need to go to their email to resume the deposition whenever they closed and reopened their browser.

I think it will be rare that people will try to simultaneously open two different depositions in two different tabs. But even if I don't find a way to detect and prevent this, it won't cause any data loss.

**Comment by rsiegl** [comment]
I agree. It has already proven to be quite convenient for me to be able to pick back up where I left off when I come back into the office. The only real instance I could see the multiple tabs problem occurring is if someone is depositing related entries and is working on both.

**Comment by rsiegl** [comment]
I can confirm this is fixed.
