### ISSUE TITLE
Changing Country or State field while loading

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#122]
This may be similar to that issue with deleting a file while it was uploading. If you go to the state or province box in the contact person loop and you change the state prior to the loading bar at the top of the screen going away it displays a "Confirm Action" message. I have included a screen shot of it below. It would appear you can do this by quickly clicking on one state then going back in and clicking another. Another way to do it, and how I coincidently came across this, is by only typing in the name. For example if US is the country tab over to state then type C then California will pop up, quickly click o and Colorado pops up. If you then wait for the screen to load the same issue occurs. This is the same behavior for the country tab (example United A pops up first then keep typing United States and it switches to the US and displays the message).

![4](https://user-images.githubusercontent.com/44450691/55989758-af129f00-5c6b-11e9-938d-83bd9fafa8ae.png)

**Comment by rsiegl** [comment]
This issue also occurs if you even were to type in something for the first name box, hit tab to get to last name and type something in before the loading bar goes away. So it would appear that this behavior is true for changing any multiple fields before the loading bar goes away. This may be related to the recent change in #121.

**Comment by jonwedell** [comment]
Thanks for the report. I suspect I know exactly what is causing this, and it should be straightforward to fix.

**Comment by jonwedell** [comment]
Actually, thinking about it more this morning I don't think the fix I deployed for this will fix it in all circumstances. I'll do some more work and update.

**Comment by rsiegl** [comment]
I was just about to mention that this was still an issue.
