### ISSUE TITLE
Invalid Release Status

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#123]
I tried this twice just to confirm. When you submit an entry with the release status "Hold for publication" it gives the following error message.

![5](https://user-images.githubusercontent.com/44450691/55991955-05cea780-5c71-11e9-9210-307b6254e0d8.png)

It let me submit them once I had changed the code to anything else.

**Comment by jonwedell** [comment]
Great catch.

**Comment by rsiegl** [comment]
I can confirm this is fixed.
