### ISSUE TITLE
Reviewing Entry Error Message

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#124]
This is very minor and may not even be an issue. Once you have deposited your entry and you are reviewing it if you drag and drop a file on the file uploader it gives the following error message:

![7](https://user-images.githubusercontent.com/44450691/55992287-d1a7b680-5c71-11e9-8385-5bfa4622313e.png)

I just thought the wording was a little unclear because the user would have internet connection they just cannot make changes to the entry once it has been submitted.

**Comment by jonwedell** [comment]
Whoa, good catch. You tried to do that even though the "drag and drop a file here" text gets removed. :)

**Comment by rsiegl** [comment]
I can confirm this is fixed.
