### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#125]
I just tried to go onto the BMRBDep and it appears it is down at the moment. I am not sure if you are working on it or something, but thought I would mention this.
![1](https://user-images.githubusercontent.com/44450691/56058632-86e87600-5d27-11e9-9d84-5fd310eb2dda.png)

**Comment by jonwedell** [comment]
This is fixed. I'm keeping the issue open to remind me to upgrade the release script to abort if the Angular build fails to ensure this doesn't happen again.

**Comment by dmaziuk** [comment]
Weird. I got the same thing, looked at the config, reloaded and it worked. Looks like a transient glitch.

**Comment by dmaziuk** [comment]
Ah, so you did  do something.

**Comment by jonwedell** [comment]
I've updated my release script to check the build error codes before actually deploying.
