### ISSUE TITLE
Unable to Deposit Entry

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#126]
I just tried to deposit an entry and the "A network or server exception occurred." error message appeared.

**Comment by jonwedell** [comment]
Can you email me the deposition ID?

**Comment by rsiegl** [comment]
Yeah. How do I get that though? When I load the entry it does not have it in the URL. It only appears there when I load the page after /load/ but goes away too quickly to copy and paste it.

**Comment by jonwedell** [comment]
You can either forward me the original deposition email, or alternatively:

Double click on the 'Deposition "depname" Navigation' text, and then open the developers console. Look at the "console" screen, and you will see the entry object. Click the arrow to expand it (it may show up with just a single letter as it's name) and then you can see the entryID (and all the other properties it has).

**Comment by rsiegl** [comment]
Gotcha. I ended up just clicking it a bunch and slowly got the deposition ID haha

**Comment by jonwedell** [comment]
Fixed.
