### ISSUE TITLE
Uploading Star file

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#127]
When you enter all your information in and then click on the button to browse for the star file, it opens up the deposition to the validate your email page. Upon validating your email it goes into a "from scratch" entry. This happens if you close the file browser as well as if you select a file. I tried putting in all the information except the email (so it could not start the deposition) and it told me I needed to add an email as expected. However, upon entering an email and attempting to begin the deposition I got the following error:

![4](https://user-images.githubusercontent.com/44450691/56064126-b8b50900-5d36-11e9-9edf-d13043261859.png)

**Comment by rsiegl** [comment]
There's still some issues with this. When I first clicked on the select a file to upload button to begin the deposition it opened the file browser, but gave me this error message.

![1](https://user-images.githubusercontent.com/44450691/56386293-fd351e80-61e6-11e9-9a5f-7c2ea2ed92cf.png)


Then once I had selected a star file the "Click to select a file to upload" button still remained alongside the start deposition button.

![2](https://user-images.githubusercontent.com/44450691/56386336-1b028380-61e7-11e9-826c-24a46fa68b63.png)

I then clicked on the start deposition button and got the following error and it remained on that page.

![3](https://user-images.githubusercontent.com/44450691/56386353-29e93600-61e7-11e9-8483-1069b4dd2904.png)


After that I then hit the begin deposition button again and it began the deposition as expected. The star file I uploaded was displayed in the "deposit data files" section. I am not sure if it should be there or if that is the behavior you were looking for?

**Comment by jonwedell** [comment]
I'm sorry, I think you tested this right as/before I was deploying the new version to the test server. These issues should be fixed if you reload the page.

Yes, adding the uploaded file as a deposited data file is a new, but intended feature. This way if they upload a complete NMR-STAR file including assigned chemical shifts, they can specify that we should parse the assigned chemical shifts from the original file.

**Comment by rsiegl** [comment]
Should there be a NMR star option for the data type to select in the drop down? Otherwise you have to have it as other kinds of data. I also may have stumbled across some odd behavior with the upload file section. I had deleted that star file originally and uploaded the data file for the entry. Now it is no longer mandatory to select the data type. Then when I put in a second file no matter what data type I select it always is red.

**Comment by jonwedell** [comment]
> Should there be a NMR star option for the data type to select in the drop down? Otherwise you have to have it as other kinds of data.

No, NMR-STAR is not a type of data, just a format of data. They would still need to specify what types of data we need to parse from the NMR-STAR - i.e. assigned chemical shifts, or constraints, etc. (This parsing then happens later during annotation - for the actual loops - the saveframes are copied) We might need to add a message making it clear why that file appears for the user, as I imagine they could also share your confusion.

> I also may have stumbled across some odd behavior with the upload file section.

This is a new bug I just introduced in another change, and have fixed. Changes are live now.

**Comment by rsiegl** [comment]
Gotcha. So ideally it would look as it does below then correct?

![1](https://user-images.githubusercontent.com/44450691/56388821-9bc47e00-61ed-11e9-8d1a-915bbfc1b606.png)

I can also confirm this is fixed.

**Comment by jonwedell** [comment]
Well, it depends. If you're pre-populating a deposition from an existing NMR-STAR file, and you also want to deposit the assigned chemical shifts in that file, then that would be correct.

If you are only using the uploaded file to bootstrap the deposition interface fields, but plan to upload a new file with assigned chemical shifts, you should just delete the first file.

@dmaziuk  - I was a little worried this could lead to confusion, which is part of why I figured they could just upload the file again. But with better help text hopefully this won't lead to confusion.

**Comment by rsiegl** [comment]
I feel like if they are making a entry they would have a new data file, rather than an existing one. I could see how the old data files in the old entry could be useful as a reference too though. I agree that the help text would take away the confusion.

**Comment by dmaziuk** [comment]
I prefer the way ADIT does, myself: we IIRC we spent a bit of time discussing it back then and decided it was the least confusing way to deal with this. I still think it's the least bad option, but that may be inertia on my part.

@rsiegl One scenario is you take a OneDep BMRB entry and make a BMRB-only deposition from it: you may have a second data file for "disordered" part of the sequence, you'd upload that _in addition_ to the data already in

**Comment by dmaziuk** [comment]
PS this actually happened at least once already.

**Comment by rsiegl** [comment]
When you upload the file the option to upload another file still remains and the file name appears next to it. The other issues are fixed though.

![1](https://user-images.githubusercontent.com/44450691/56390905-cd8c1380-61f2-11e9-9adb-100916c62c68.png)

**Comment by jonwedell** [comment]
@rsiegl - That behavior is on purpose, I just added it in. It's there to allow you to select a different file if you accidentally selected the wrong file the first time. The file name appears so that you know what you uploaded. (The name also appears on the "start deposition" button, but users are used to seeing it next to the "Choose file" button on most web sites, so I put it there too.) Please leave this open until I can implement the code referenced below.

@dmaziuk - I thought about this more last night, and I think there is a best-of-both-worlds solution possible. When a user starts a new deposition from an existing one, the code can actually analyze the types of data present in that file, and automatically select them in the file upload interface. (If they upload a file with real chemical shift data, assume they want to deposit it.) Then they can uncheck a data type if they don't intend to deposit it from the originally uploaded file. I think this would better support the "default case". It's not that error prone either - this will make the assigned chemical shift section appear, where they will have to select which file has the data, and they will see just the original uploaded file. If this is the wrong file, they will then likely realize they need to upload their additional data file.
