### ISSUE TITLE
Ordering of Sections on Review Page

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#128]
I recall this being a topic of conversation quite some time ago because of having to put the entity in prior to the molecular assembly. I just noticed that when the sections are not filled out on the review page, it puts them in the order they appear in the star file rather than the order in the side nav. I was wondering if this should be reordered?
![1](https://user-images.githubusercontent.com/44450691/56240063-1f4c6680-6058-11e9-8792-fbf16ec79964.png)

**Comment by rsiegl** [comment]
I can confirm this is fixed.

**Comment by rsiegl** [comment]
I may have spoke to soon on this. They're in the correct order, but now none of the buttons work besides the return to previous page.

**Comment by jonwedell** [comment]
Ahh, sorry. Fixed, but will take a bit to deploy.

**Comment by jonwedell** [comment]
Deployed.

**Comment by rsiegl** [comment]
I can confirm this is fixed.
