### ISSUE TITLE
Return to previous page not working

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#130]
When you click on the link to return to your entry and you have all of the required parts filled out it brings you to the review page as expected. When you click the "return to previous page" button it reloads the review page and does not go to the previous page. Once you use the menu to go to other sections and go back to the review page the button then works.

**Comment by jonwedell** [comment]
There is no "previous page" if you just opened the deposition from the link in the email. The "return to previous page" button is basically just another way to click the "back" button in the browser, it doesn't return to the final section of the entry.
