### ISSUE TITLE
Contact person loop in Uploaded star file deposition

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#135]
When you upload a star file to do a deposition the first two rows are always mandatory even if there are other "principal investigator" and "responsible scientist" rows present. Is this the desired behavior for this or should you be able to delete the second row if there are multiple present?

![1](https://user-images.githubusercontent.com/44450691/56386724-34f09600-61e8-11e9-9b64-3780547c6e1d.png)

**Comment by jonwedell** [comment]
You can now delete the second row, as long as there are at least 3 rows. Furthermore, it won't add a second blank row to begin with, at least for contact person. It does for authors, to make sure you have a spot to enter your own name if it wasn't in the other entry.

**Comment by rsiegl** [comment]
This works now, but you can now have it so either the principal investigator or the responsible scientist is not present. For example you make the third row then delete the second row. Now there is two principal investigators, but no responsible scientist. You could always change that in the drop down, but people might not do that. Should it be that you can only delete a row if there is another row with the same "Role of this person in the project" value? I could see that being difficult since you could always change that value from the drop down.

**Comment by jonwedell** [comment]
The rule that "each entry must have at least one PI" is still enforced, even if you delete rows. I don't think we have any rules against two PIs, or rules that require at least one responsible scientist.

**Comment by rsiegl** [comment]
Gotcha. I can confirm this is fixed then.
