### ISSUE TITLE
Contact us button does not work

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#136]
I am not sure if you have to configure your email a certain way or something, but when I click on the "contact us" button on the homepage nothing happens.

**Comment by jonwedell** [comment]
It should open up an e-mail in your e-mail client. Perhaps behind the browser window?

**Comment by jonwedell** [comment]
Long term I was planning on replacing this with a form on the website to enter feedback, like there is now on the BMRB home page.

**Comment by rsiegl** [comment]
That is a nice touch to the BMRB home page! 

The contact us button does not bring up an email for me anywhere, even on the BMRB home page at the bottom where it says "
Contact bmrbhelp@bmrb.wisc.edu if you have any questions about this site". I even tried writing my own HTML to test it and it did not work. Perhaps this is just an issue on my machine then. I can keep this issue open though to track the progress for the new "feedback" or "support" feature you plan on implementing.

**Comment by dmaziuk** [comment]
It's in the browser "file associations", or whatever they're called today, you need to figure out the one that's used to open "mailto" links. If that is set use the "default mail program", that's in your desktop settings (control panel?) under "preferred applications" or something along those lines.

**Comment by jonwedell** [comment]
> I can keep this issue open though to track the progress for the new "feedback" or "support" feature you plan on implementing.

Yes, this is perfect.

**Comment by jonwedell** [comment]
Actually, I'm going to close this, as the same issue is tracked in #61.
