### ISSUE TITLE
Experiment file section

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#137]
I do not recall seeing this field in this section before. It is also mandatory. The name of the file corresponds to a number field and the file one has no options in the drop down.

![1](https://user-images.githubusercontent.com/44450691/56389501-5903a580-61ef-11e9-9857-a733f43884f1.png)

**Comment by jonwedell** [comment]
Yes, this is new, and is currently broken until I add new code to handle a loop-to-loop conditional rule. I'll keep this issue open to track development of that.

**Comment by jonwedell** [comment]
This should now only appear when there is time-domain data.

**Comment by rsiegl** [comment]
I can confirm this is fixed.
