### ISSUE TITLE
Old entry odd behavior on NMR experiments used to derive these data 

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#141]
This may be just because this was an older entry, but this is what I have popping up in this tag.
![1](https://user-images.githubusercontent.com/44450691/56765508-d8075980-676c-11e9-989b-9ef08b97ad3c.png)

I'll email you the entry ID.

**Comment by jonwedell** [comment]
The "n/a" you mean? That is rectified in new dictionary versions.

Or are you surprised with the value in the enumeration? That is a new addition to better handle selecting an experiment.

**Comment by rsiegl** [comment]
The value in the enumeration. It will not let me change it and is always red.

**Comment by jonwedell** [comment]
Closing, as this is just a result of the old dictionary.

**Comment by jonwedell** [comment]
This is still broken with from-scratch depositions, though it was working fine with from-existing ones.

**Comment by rsiegl** [comment]
I just did an entry from an existing BMRB entry by number, since that allows you to select the experiments like you showed me, but it still would not let me deposit. Everything was filled in and nothing red, but still showed the network or server exception has occurred.

**Comment by rsiegl** [comment]
I can confirm this is fixed.
