### ISSUE TITLE
Dipole-dipole cross correlation saveframe does not allow selection of dipole-dipole cross correlation data file

### ISSUE THREAD

**Issue by mvandervennet** [uwbmrb/BMRBDep#144]
I was testing the BMRBDep system with entry 27350, which has
dipole-dipole cross correlation relaxation data. When filling out the
save frame for this data, the data files I labeled as dipole-dipole
cross correlation data would not appear when I clicked on the
"deposited data file name" section. I have attached a
screenshot of the section I am talking about.

![snapshot](https://user-images.githubusercontent.com/43587794/59634207-d70efa80-9113-11e9-83d8-583e70737b62.jpeg)

**Comment by jonwedell** [comment]
Probably same underlying issue as in #143.

**Comment by jonwedell** [comment]
Resolved [in dictionary](https://github.com/uwbmrb/nmr-star-dictionary/commit/9a051d067a7aac52d42c3e24c3ca5bfe1a30ab1c).
