### ISSUE TITLE
Improve handling of nmr-star v2 uploads

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/BMRBDep#145]
- Add message to deposition interface that v2 is not supported
- Improve error message if v2 file is detected uploaded rather than generic message
- ... or support V2 if possible, using the converter?

**Comment by dmaziuk** [comment]
there's ~50 2.1 entries that failed to convert to v 3 so in general you can't guarantee the conversion will work. Of course that's about 0.5% of the entries, so... I'd put the converter up as a stand-alone tool though. 

One problem is Steve's `s2nmr` maps would need to be updated for the latest dictionary and they're not very easy to figure out. Spending time on that or on rolling your own for the sake of how many 2.1 files are being generated these days? -- may not be worth it.

**Comment by jonwedell** [comment]
> One problem is Steve's `s2nmr` maps would need to be updated for the latest dictionary and they're not very easy to figure out. Spending time on that or on rolling your own for the sake of how many 2.1 files are being generated these days? -- may not be worth it.

I actually don't think they need to be updated. The deposition system itself can handle a (potentially lossy, but it's only a best-effort) conversion from v3.low to v3.current. So we should be able to use the s2nmr converter to convert v2 to v3.low, and then they can use that to start a deposition without issues.

Worst case scenarios are that:

1) Some data is lost. They are still better off than starting from scratch.
2) Some data is converted into the wrong tag (if this happens, it would be happening in s2nmr). In this case they will see the wrong data in the deposition interface, and be responsible for fixing it.

Both seem preferable for a user than not accepting the file at all, or forcing them to take additional steps to do the conversion themselves.

The main catch is that integrating s2nmr into the new deposition system (especially getting it to run in the Docker container) may indeed not be worth the work.

**Comment by jonwedell** [comment]
Points 1 and 2 addressed in 5f92847 and 20c7f78.

**Comment by jonwedell** [comment]
Closing without adding s2nmr. Based on the experience with the user who tried to deposit v2 data, it was due to confusion on the depositor's part. It is probably best to not help people upload v2 data - they can always contact us for help, and then we can verify the v2 file is correct, and run s2nmr in house for them.
