### ISSUE TITLE
Contact person name fields not linked to Entry author name fields

### ISSUE THREAD

**Issue by elulrich** [uwbmrb/BMRBdep#157]
Contact name fields are enumeration tied to Citation author fields but not to Entry author fields. This is moving forward. Enumeration ties are in the dictionary.

**Comment by jonwedell** [comment]
Can you explain a bit more? I currently see contact person, entry author, and citation author all being linked via enumeration tie. Are you saying this shouldn't be the case going forward?

**Comment by elulrich** [comment]
Hi,

After leaving the entry information section and then going back, I now 
see a list to select from. Interesting.

Thanks,
Eldon

**Comment by jonwedell** [comment]
This is the same issue as #149.

**Comment by jonwedell** [comment]
This was due to how the filtering of the new Angular Material open enum was implemented. It is indeed a separate issue from #149 which will need some more significant refactoring to address.
