### ISSUE TITLE
BMRBdep forces me to add second contact person

### ISSUE THREAD

**Issue by perzeus** [uwbmrb/BMRBdep#163]
After I filled the contact person data, it still shows a row for a second contact person, with all fields in red, and no button for removing the row. I cannot pass the "review deposition" phase because is sending me to "entry information" to fill that second contact person.

**Comment by jonwedell** [comment]
This is a business rule we're implemented just for the contact person loop. We require* two contact persons for each deposition.

* In the rare case where there truly only is one contact person, we've in the past had authors submit their name twice.

I can remove the restriction on removing the second row if we want to change our policy, but it is currently there on purpose. @elulrich

**Comment by perzeus** [comment]
OK. That clarifies the issue. Thanks.
