### ISSUE TITLE
Contact person's "role" field only accepts PI selection

### ISSUE THREAD

**Issue by perzeus** [uwbmrb/BMRBdep#164]
When selecting the contact person role, any selection other than "Principal Investigator" makes the field remain red-shaded, as if the "role" field has not been filled.

**Comment by jonwedell** [comment]
This is also a business rule. Each deposition must contain at least one "Principal Investigator". Any contact person may be the PI, but at least one must have that value.

If you hover over the red shaded area, it will give a message explaining that. Perhaps we can improve how we display the error messages?

**Comment by perzeus** [comment]
I see. I realized I never hovered over the field long enough to get the error message. My bad. Thanks again.

**Comment by jonwedell** [comment]
Well, this is still useful feedback. If you didn't realize there was a specific message to be seen by hovering, it is likely other depositors didn't either. I'm going to re-open the ticket to keep the topic of "how do we improve error message display" on my radar. Or at least, "how do we better document".

**Comment by elulrich** [comment]
Edited prompt help information - not tested
