### ISSUE TITLE
NMR experiment link to experiment files is not working properly

### ISSUE THREAD

**Issue by elulrich** [uwbmrb/BMRBdep#166]
Most of the problem appears to be in the dictionary. Require Jon to check out to see if fix works.

**Comment by jonwedell** [comment]
What exactly about it isn't working?

**Comment by elulrich** [comment]
Jon, will need you to check to make sure the correct fields are being linked (is a special case).

**Comment by elulrich** [comment]
Both the ID tag and the name tag present in the interface (dictionary problem). Also, content field needs to be mandatory, again dictionary. I will be making the 'name' tag hidden. This tag is not the one that is linked to experiment_name, sample, etc.

**Comment by elulrich** [comment]
Fixes put into dictionary - new version NMR-STAR v3.2.4.1 pushed

**Comment by elulrich** [comment]
I fixed the dictionary (hopefully). Let me know when a new version is 
available for testing. I will be off-line for a couple of hours, but 
will keep going with this version for now.

Thanks,
Eldon

**Comment by jonwedell** [comment]
> Both the ID tag and the name tag present in the interface (dictionary problem).

I see, yes. Thanks for fixing this.

> Also, content field needs to be mandatory, again dictionary.

There is a problem here. I believe the only files that they are allowed to select for '_Experiment_file.Name' are ones that are of type "Time domain".

So they would have to upload the file, mark it "Time domain" and then in this section set the content type to, for example, "Pulse field gradient".

**Comment by jonwedell** [comment]
New version is live now. Looks good in my local testing.
