### ISSUE TITLE
Add example to prompt for BMRB entry selection on initial page

### ISSUE THREAD

**Issue by elulrich** [uwbmrb/BMRBdep#175]
Many may think that a BMRB accession code includes 'bmr' so would be good to have an example of a BMRB accession code in the prompt. Just a code in parenthesis '(15000)' at the end of the prompt.

**Comment by jonwedell** [comment]
I've updated the validation error message if they have entered an invalid BMRB ID to say `Not a valid BMRB ID. BMRB IDs consist only of numbers. (For example: 15000)`.
