### ISSUE TITLE
Sample default to three rows for content.

### ISSUE THREAD

**Issue by elulrich** [uwbmrb/BMRBdep#176]
Virtually all samples have more than one component. Should ask Hongyang, but I am worried that depositors are including only one compound, because only one row is the default in the sample contents table.

**Comment by jonwedell** [comment]
I just looked at 10 random entries that have been deposited, and all have more than one component in the sample. It's easy for me to default the sample to three loops, but I'm not sure if we need to.

**Comment by elulrich** [comment]
I would default to three. This saves them the time of creating new rows. The current version has three rows in first sample, but when a new sample is created there is only one row.

**Comment by jonwedell** [comment]
Confirmed resolved.
