### ISSUE TITLE
File upload problem

### ISSUE THREAD

**Issue by elulrich** [uwbmrb/BMRBdep#179]
Could not upload a new file in middle of deposition. Kept getting error message something like 'do you have an internet connection'. Same message at several points in deposition. Finally, ended session and then restarted and all of the uploaded files appeared. Tried to delete a couple of the uploaded files and again received 'do you have an internet connection'. When clicked on 'Notify us' received a message that 'Mail' needed to upload messages.

**Comment by elulrich** [comment]
Tried to reproduce but could not. The previous deposition with the problem had been open for a long time (hours). Is it possible that something timed out on our servers for the deposition?

The deposition that had problems was test110 and was deposited.

**Comment by jonwedell** [comment]
Should be fixed. It appears a newer version of the gitpython library I upgraded to in this release has an intermittent bug. I've reverted back to the previous version.
