### ISSUE TITLE
Resume deposition

### ISSUE THREAD

**Issue by kumar-physics** [uwbmrb/BMRBdep#191]
I started a deposition some time ago on the dev site and I wanted to resume that deposition. In order to resume the deposition it says "To resume your deposition, simply click the link in the e-mail you were sent when you created the deposition." The problem is I don't know what key word or subject I should look for in my mail box. I tried to search the keyword 'bmrbdep'  and I get hundreds of hits because of the messages from the GitHub. 
I would suggest that we should provide more information to resume a deposition, something like 
""To resume your deposition, simply click the link in the e-mail you were sent when you created the deposition _**with the subject 'some unique subject message to find the mail easily'**_ "

**Comment by jonwedell** [comment]
Closed in 67a7475e.
