### ISSUE TITLE
The contact person loop has too many fields to render well on most screen sizes

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/BMRBDep#31]
Consider some sort of alternative layout for loops with many values?

**Comment by jonwedell** [comment]
Is it still relevant to collect a fax number these days?

**Comment by jonwedell** [comment]
@elulrich - Is it still relevant to collect a fax number these days?

**Comment by elulrich** [comment]
Agree, we can drop the fax number! I will alter dictionary.

**Comment by jonwedell** [comment]
Updated the override rules to hide Address_3 unless Address_2 has a value. This should also make this loop slightly less cramped.

**Comment by rsiegl** [comment]
@jonwedell Yesterday you had mentioned that you would like to make this loop have a scroll bar (if it does not render well on the screen). I was not sure if you had any ideas for that, but I found an example where they use `<div>` around a `<table>` and implemented `style="overflow-x:auto;"` for the in line CSS of the `<div>` element.

https://www.w3schools.com/css/tryit.asp?filename=trycss_table_responsive

**Comment by jonwedell** [comment]
Great, thanks for looking into this more; I'll try it out and see how it looks!

Also, I should spend a little time getting you more introduced to the code base and Git - if you're interested, that is. Then you could actually make whatever changes you want in your own branch, and if you think they look good, "submit" them for review via a pull request, whereby I'll accept them if I don't see any problems.

**Comment by rsiegl** [comment]
That sounds awesome, I would for sure be interested in doing that. Looking forward to when you get back! Hope you are having a great vacation and have a nice trip next week!
