### ISSUE TITLE
Country and state/provenance pull downs

### ISSUE THREAD

**Issue by elulrich** [uwbmrb/BMRBDep#66]
Nice to have pull downs for these fields. Linked pull downs even better. Idea of top five countries at top of pull down would be great - take from analysis of our current deposition sources.

**Comment by jonwedell** [comment]
> @elulrich - Can you move the country selection to be above the state/province selection in the dictionary? Otherwise it leads to a confusing user experience as there are no state/provinces available to select.

To go further, I think the ideal order would be:

Country
State or province
City
Mailing address (line 1)
Mailing address (line 2)
Mailing address (line 3)
Postal code

**Comment by jonwedell** [comment]
Okay, this is implemented. However, you may notice a bug. If you select a country with a non-ASCII character, there are oddities in the behavior. (Specifically, the value does not show as selected.) I know exactly why this is happening: because the selected value is automatically having all non-ASCII values stripped. It doesn't appear that the library I'm using has any mechanism to display an ASCII-equivalent version of the country names.

There are a few ways we could deal with this... but first - both the interface code, the API, and the PyNMRSTAR library are fully capable of dealing with Unicode NMR-STAR files. Is creating them still out of the question due to other software in the pipeline and other compatibility requirements? Yes, it would be an extension of the official STAR spec, but we have already made other tweaks to it as well. Perhaps we should discuss in person with Dimitri.

**Comment by elulrich** [comment]
Easy to change order. Slight modification to your order, how about putting Postal code after City? The first fields are all small fields. Also, is it possible to provide a short list of postal codes once the City is selected? Or can this be filled in completely after knowing the street address?

**Comment by elulrich** [comment]
Not sure of all the technical aspects, but going to Unicode beyond ASCII could have real problems in interfacing with the PDB, unless they go to Unicode.

**Comment by jonwedell** [comment]
> Slight modification to your order, how about putting Postal code after City?

Agreed, that is a better order.

> Also, is it possible to provide a short list of postal codes once the City is selected? Also, is it possible to provide a short list of postal codes once the City is selected?

Yes, but I think we would need an up to date subscription to an API like [this one](https://smartystreets.com/docs/cloud/us-zipcode-api) to do so. This is more complex an error prone than the country/province auto options for several reasons. I think we could add it as a future "enhancement" just to remember the idea, but I wouldn't want to focus on it until we have a beta version live.

**Comment by rsiegl** [comment]
I was just going through a deposition and as of now the order has city then state then country, etc. So it appears the new ordering has not gone into effect yet unless that was to be implemented later.

**Comment by jonwedell** [comment]
It hasn't, but I believe it's due to a problem somewhere other than the dictionary itself, as I confirmed earlier that the dictionary has them in the correct order.

Also, the ordering change will only apply to new entries created after I work out whatever the issue is.

**Comment by jonwedell** [comment]
Okay, the tags are confirmed showing up in the correct order now, after I fixed an issue in the API (https://github.com/uwbmrb/BMRB-API/commit/0e097d3).

**Comment by jonwedell** [comment]
Reopening until the default country is set to USA. @elulrich - can you set the 'default value' for the _contact_person.Country tag to 'United States'? That will make it autofilled, and I think it is more appropriate to have that in the dictionary versus hardcoded in the app.

**Comment by jonwedell** [comment]
Reopening until the default country is set to USA. @elulrich - can you set the 'default value' for the _contact_person.Country tag to 'United States'? That will make it autofilled, and I think it is more appropriate to have that in the dictionary versus hardcoded in the app.

**Comment by elulrich** [comment]
I think autofilling the country with United States as a default is politically not the thing to do. People in other countries get upset when an organization that they expect to be world wide biases their systems toward one country. We have this kind of problem with the RNA community believing that everything is biased toward proteins. I would prefer that the top five or 10 countries be at the top of the pull down list.

**Comment by jonwedell** [comment]
Okay, this is implemented in b83e505. I ran the numbers, and the top 6 countries were:

- US
- Great Britain
- China
- Japan
- Australia
- Mexico

**Comment by rsiegl** [comment]
I can confirm that the top six countries listed are those now.
