### ISSUE TITLE
Confusing that coloring for mandatory and fields with errors is the same rose color

### ISSUE THREAD

**Issue by elulrich** [uwbmrb/BMRBDep#67]

**Comment by rsiegl** [comment]
A yellow could be used to indicate a field with an issue/error, while the mandatory ones remain the rose color.

**Comment by jonwedell** [comment]
I'm having second thoughts about implementing this. The Angular material design guidelines strongly suggest to never use more than three shades of color on a page, and we already have three. (grey, blue, and the salmon "error" color).

@elulrich  - How strongly do you feel about this? My intention was "salmon = you need to do something" where the "you need to do something could be either "enter a value" or "correct your value". You'll notice on the [home page](https://dev-bmrbdep.bmrb.wisc.edu/) that the fields turn red if you tab through them without entering a value, or if you enter an invalid value. That's the default behavior of the module.

What do you think?
