### ISSUE TITLE
Period for initials

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#82]
When we annotate entries we always add a period after an initial. An added improvement to the new deposition system could be to automatically add a period after any initial if one does not currently exist.

**Comment by jonwedell** [comment]
Do you still use "nn -fix" during the annotation process?

**Comment by jonwedell** [comment]
Interesting. I can add this to the final "deposition" step.

**Comment by jonwedell** [comment]
Which specific tags do you apply this to, and do you only apply it if the tag only contains a single character?

**Comment by rsiegl** [comment]
_Contact_person.Middle_initials
_Entry_author.Middle_initials
_Citation_author.First_initial
_Citation_author.Middle_initials
Are all of the tags that a period is added to. It is typically just one letter and then the period is added to the end. I have seen multiple initials though for example:  "KD" and then I change it to "K.D." I have not run across another example with the old deposition system yet.

**Comment by jonwedell** [comment]
This is implemented, but it only happens during final deposition, so to check it you will need to look at the NMR-STAR file you are e-mailed after deposition is complete.

**Comment by rsiegl** [comment]
I tried this with two different entries, 872cf293-e0f1-453b-b996-5fc8e1e0516d and 1717408a-6e1f-4525-9de8-0f2d3b2a2b7d and it did not add the period for either. I put the initials without the period in the entry author section.

**Comment by rsiegl** [comment]
I can confirm this is fixed
