### ISSUE TITLE
Re-do side nav to look cleaner

### ISSUE THREAD

**Issue by jonwedell** [uwbmrb/BMRBDep#84]
Already been doing some work on this, but creating an issue to track it and get feedback.

**Comment by rsiegl** [comment]
You must have recently changed this, but I was going to suggest category headers be bold or larger to distinguish from the sub-categories. Another way to distinguish what you are selected on vs other categories could be to have it underlined as well as bold. Overall I think it looks nicer than the previous one and makes sense

**Comment by jonwedell** [comment]
I've added a darker background highlight to show to active section. It also automatically scrolls to the super category in which the section you are viewing is contained.

**Comment by rsiegl** [comment]
In regards to the automatic scrolling. I have noticed that when you open the side menu it jumps around for a second or so (to automatically scroll obviously). I have opened the menu and tried to click on a category and found myself clicking the wrong one due to the menu jumping. Is it possible that the menu could automatically scroll "in the background" rather than only when you open it?

**Comment by jonwedell** [comment]
I noticed that as well and was trying to fix it. When you use an Angular "Menu" element, Angular automatically scrolls to the first element in the menu - which is the "Deposit Entry" button. Only after it scrolled there can I scroll down to where you would expect it to be. That is what makes it appear to jump around.

I think this will be fixed once I redo the menu again using a different type of Angular element, which I plan to do next week. It doesn't appear there is any way to disable the automatic scrolling to the first menu element. :|

**Comment by rsiegl** [comment]
I can confirm this is fixed. Not sure if you wanted me to close this issue in case you wanted to do more work on the side nav at a later time.

**Comment by jonwedell** [comment]
It will have to be updated a bit when we add the deposition manager, but I'll close this for now and we can use the deposition manager issue to track that. Thanks.
