### ISSUE TITLE
NMR Experimental descriptions check mark

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#89]
In the side menu, when you fill out this section, you cannot see the check mark to indicate this section is completed. I think this is because the check mark goes at the end of the text, but this text is too long and becomes "NMR experimental descripti..." in the side menu.

**Comment by jonwedell** [comment]
This one is going to be difficult to fix.

Do you think it would be okay to have the check mark and incomplete symbols to the left of the section names?

**Comment by jonwedell** [comment]
For me the check mark is only missing when "NMR experimental descriptions" is the active tab. Is this also the case for you, or is it always missing?

**Comment by rsiegl** [comment]
I just noticed that if you delete a saveframe that was not completed, whatever section that saveframe is under pops up as not completed (with the exclamation mark in the circle). For example, if you duplicate a sample conditions section, it will not have a name and remain red. When you delete it the saveframe goes to the deleted section as expected. The sidebar menu will still show it as not filled in. 

I am guessing this can easily be fixed by incorporating the tracer, or whatever was used to put the saveframe in the deleted section, to the coding of if a section is complete or not.

**Comment by jonwedell** [comment]
> I just noticed that if you delete a saveframe that was not completed, whatever section that saveframe is under pops up as not completed (with the exclamation mark in the circle).

This is fixed, thanks. It was a simple fix indeed - the code to check if a category was complete should only apply to saveframes that aren't deleted. e65c7f9

**Comment by rsiegl** [comment]
I can confirm this is fixed.
