### ISSUE TITLE
Molecular Assembly question mark page

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#90]
1. Under Ligands, cofactors and non-standard residues "In the ADIT-NMR section where ligands, cofactors and non-standard residue are described..."
should say "In the ADIT-NMR section where ligands, cofactors and non-standard residues are described..."

2. Under molecular assembly (assembly) the second to last sentence
"For molecular assembly shown..."
should say "For the molecular assembly shown..."

3. Under the first example step 1 is missing a period.

4. Under example 2 step 3 it refers to the "Save Changes" button that we no longer have twice.

5. Under example 2 step 5 it refers to the "Save Changes" button that we no longer have.

6. Under example 3 step 3 it refers to the "Save Changes" button that we no longer have twice.

7. Under example 3 step 6 it refers to the "Save Changes" button that we no longer have.

8. The "Return to previous page" button only appears at the bottom of this page. Should it also appear at the top like the rest of the pages? I would get why we would only want it once at the bottom of the page too (so the depositor has to read through the instructions before returning to the deposition ideally).

**Comment by dmaziuk** [comment]
and it probably shouldn't mention ADIT-NMR

**Comment by jonwedell** [comment]
All of these fixed, including the ADIT mentions.

I'm tempted to leave the "Return to previous page" button at the bottom, as if they want to return earlier they can pull up the navigation menu and go back.

**Comment by rsiegl** [comment]
I have not seen the changes go into effect yet on my end. There was another ADIT-NMR mention at the top that I had not mentioned, but I am assuming you saw that as well.

Yeah upon thinking about it for a day I agree with you that it is not necessary to have the top "Return to previous page" button.

**Comment by jonwedell** [comment]
Ah, apologies - I forgot to push to the development server. Should be there now.

**Comment by rsiegl** [comment]
Perfect, I can confirm all the issues here are fixed.
