### ISSUE TITLE
Enumerations are missing

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#91]
I am not sure if this is just because they are currently being worked on or if this is a bug of some sort. None of the enumerations, except for those made in the entry like the NMR experiments from the experiment list, are working. Along with that the chemical shift references drop down menus are gone (no, yes and yes with IUPAC).

**Comment by jonwedell** [comment]
This is fixed with the schema loading fix.

**Comment by rsiegl** [comment]
I had tried to access the site and it is not loading at the moment...Not sure if someone took it down for some reason or something like that.

**Comment by jonwedell** [comment]
Down as we switch to a containerized version of it. Should be back online by the end of day tomorrow - I will update here.

**Comment by jonwedell** [comment]
@rsiegl - More work than I anticipated, but Dimitri and I have got the new containerized version running. None of the old depositions were migrated. The enumerations issue is fixed. Thanks for your patience.

**Comment by rsiegl** [comment]
Perfect. I have to head out shortly for an exam, but will go through testing on Tuesday when I get in.

**Comment by rsiegl** [comment]
I can confirm this is fixed.
