### ISSUE TITLE
Refresh issue with Molecular assembly description

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#92]
When you are on the Molecular assembly description page, if you refresh the page the menu button at the top left on the toolbar goes away. This happens when you refresh the page normally as well as when you do the developers tool refresh. The return to the previous page button at the bottom still remains though so you can still return to the entry.

**Comment by jonwedell** [comment]
I really can't sneak anything past you. 😂

I'm aware of this one, and there is an "easy fix" I could do but it's symptomatic of a larger issue in the way that deposition sessions are loaded and managed. I've been thinking of ways to refactor the code that wouldn't only solve this issue but would also give other improvements. This code would also need to be re-worked when we add the "deposition management" page to view all sessions.

For example, I was considering removing the deposition ID from the URL entirely, and instead letting the user load sessions via the deposition management page. Anyways, I haven't yet decided on the best way to address this issue, so I'm going to use this issue to track the "refactor session management" task. 👍

**Comment by jonwedell** [comment]
For now I've fixed this issue in place, but long term it should stop mattering once the new deposition loading system is in place.
