### ISSUE TITLE
Incomplete fields in deleted saveframes

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#93]
If you have deleted saveframes that contain missing required fields they still appear on the "Review deposition" page. You cannot deposit the entry until you have put something in the required fields (even though these saveframes will not be used in the actual entry).

**Comment by rsiegl** [comment]
I just tried to do this and it still would not let me deposit unless the deleted saveframe was filled out.

**Comment by jonwedell** [comment]
I think I forgot to push to production. Can you retry?

I'm going to add a way to check that the version you see at dev-bmrbdep.bmrb.wisc.edu contains the latest changes next week so you'll be verify the newest version is live.

**Comment by rsiegl** [comment]
I can confirm this is fixed.
