### ISSUE TITLE
BMRBDep button 

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#94]
At any point in the entry you can click the BMRBDep button at the top of the page on the toolbar. When you do this it brings you to the BMRBDep page as expected. The odd thing is that the menu button remains on the toolbar when you are at the BMRBDep page and you can click on it to be taken to whatever section you choose of the entry you were just working on. I think the menu button should no longer be present when you do this. Also it may be beneficial to have a pop up that says something along the lines of "You are about to exit your entry deposition, would you still like to navigate to the BMRBDep page?"

**Comment by jonwedell** [comment]
This will also be addressed by the refactor that will fix #92.

**Comment by rsiegl** [comment]
I can confirm this is fixed.
