### ISSUE TITLE
Restore data page and menu highlight

### ISSUE THREAD

**Issue by rsiegl** [uwbmrb/BMRBDep#96]
When you go to the Restore data page, the menu leaves whatever section you were previously on highlighted. I am not sure if we would rather have the "Deposition Options" section highlighted or nothing highlighted or leave this as it is.

I am assuming it currently works this way in the hopes that the depositor is on a certain page, realizes they want to restore a saveframe that is on that page, they go and restore it, then on the restore page they can click the menu and their previous page is already highlighted so it is more clear where they just were?

**Comment by jonwedell** [comment]
> I am assuming it currently works this way in the hopes that the depositor is on a certain page, realizes they want to restore a saveframe that is on that page, they go and restore it, then on the restore page they can click the menu and their previous page is already highlighted so it is more clear where they just were?

That would have been a reasonable thing to do, but I actually don't know why it still highlights that section. :) This should be fixed when I redo the side elements as mentioned in #84.

**Comment by rsiegl** [comment]
I can confirm this is fixed.
